export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const UPDATE_SELECTED_FORM = "UPDATE_SELECTED_FORM"; //
export const UPDATE_SELECTED_FORM_FIELDS = "UPDATE_SELECTED_FORM_FIELDS";
export const UPDATE_SELECTED_INDEX = "UPDATE_SELECTED_INDEX";
